<div id="userengage">
  <form method="post" action="<?php echo $this->getUrl('*/*/post'); ?>">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
      <div class="logo"></div>
      <div><label for="userengage_apikey">Your Api Key:</label><br>
          <input type="text" class="input-text" name="userengage_apikey" id="userengage_apikey" value="<?php echo Mage::getStoreConfig('userengage/general/apikey'); ?>" /><input type="hidden" name="userengage_apiKey" id="userengage_apiKey" value="0"><br><p>Please enter your application key which has been sent to your email address.<br>The api key is a 64 letter and number key.</p><p><strong>Your API key can be found here:</strong><br><a href="https://app.userengage.io/clients/integration/" target="_blank">https://app.userengage.io/clients/integration/</a><br>If you have problems with this installation, feel free to contact us.</p><button type="submit">Save</button>
        </div>
    </form>
  </div>
</div>
