<?php

    $apiKey = Mage::getStoreConfig('userengage/general/apikey');
    if (Mage::getSingleton('customer/session')->isLoggedIn() > 0) {
        $customer               = Mage::getSingleton('customer/session')->getCustomer();
        $custName               = $customer->getName();
        $custEmail              = $customer->getEmail();
        $customerAddressId      = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling();
        $address                = Mage::getModel('customer/address')->load($customerAddressId);
        $company                = $address->getCompany();
        $city                   = $address->getCity();
        $countryCode            = $address->getCountryId();
        $telephone              = $address->getTelephone();
        $groupId                = Mage::getSingleton('customer/session')->getCustomerGroupId();
        $group                  = Mage::getModel('customer/group')->load($groupId)->getCode();
        $create_at              = date("Y-m-d", Mage::getModel("core/date")->timestamp($customer->getCreatedAt()));
        $wishlist               = Mage::getModel('wishlist/wishlist')->loadByCustomer($customer, true);
        $wishListItemCollection = $wishlist->getItemCollection();
        $wishListTotal          = 0;
        $wishListItems          = array();
        foreach ($wishListItemCollection as $item) {
            $_product        = $item->getProduct();
            $wishListTotal   = $wishListTotal + $_product->getPrice();
            $wishListItems[] = $_product->getName();
        }
        $wishListTotalPrice = Mage::helper('core')->formatPrice($wishListTotal, false);
        $cartItem           = Mage::helper('checkout/cart')->getItemsCount();
        $cartTotal          = Mage::helper('checkout/cart')->getQuote()->getGrandTotal();
        $cartTotalPrice     = Mage::helper('core')->formatPrice($cartTotal, false);
        $customerTotals     = Mage::getResourceModel('sales/sale_collection')->setOrderStateFilter(Mage_Sales_Model_Order::STATE_CANCELED, true)->setCustomerFilter($customer)->load()->getTotals();
        $customerOrders     = $customerTotals->getNumOrders();
        $customerLifetime   = Mage::helper('core')->formatPrice($customerTotals->getLifetime(), false);
        echo '<script>window.civchat = {'.
             'apiKey:"' . $apiKey . 
             '", name:"' . $custName . 
             '", email:"' . $custEmail . 
             '", "customer_company":"' . $company . 
             '", "customer_location":"' . $city . 
             '", "customer_country":"' . $countryCode . 
             '", "customer_phone":"' . $telephone . 
             '", "customer_group":"' . $group . 
             '", "customer_lifetime_sales":"' . $customerLifetime . 
             '", "customer_orders":"' . $customerOrders . 
             '", "customer_create_date":"' . $create_at . 
             '", "customer_cart_items":"' . $cartItem . 
             '", "customer_cart_total":"' . $cartTotalPrice . 
             '", "customer_wishlist_items":"' . count($wishListItems) . 
             '", "customer_wishlist_total":"' . $wishListTotalPrice . 
             '"};</script>';
    } else {
        echo '<script>window.civchat = { apiKey:"' . $apiKey . '"};</script>';
    }
?>
<script src="https://widget.userengage.com/widget.js"></script>